#:schema https://mise.jdx.dev/schema/mise.json

[tools]  # tombi: format.rules.table-keys-order = "ascending"
# tools to use on all my projects
action-validator = "0.9.0"
actionlint = "1.7.12"
editorconfig-checker = "3.8.0"
ghalint = "1.5.6"
pinact = "4.1.0"
"pipx:gh-action-pulse" = { version = "1.0.0", uvx = true }
prek = "0.4.10"
rumdl = "0.2.34"
shellcheck = "0.11.0"
shfmt = "3.13.1"
tombi = "1.2.0"
uv = "0.11.28"
yamlfmt = "0.21.0"
yamllint = "1.38.0"
zizmor = "1.27.0"

# To checks links
lychee = "0.24.2"
